# Global configuration settings.
collapsiblock.settings:
  type: config_object
  label: 'Collapsiblock global settings'
  mapping:
    default_action:
      type: integer
      label: 'Default block collapse behavior'
      translatable: false
      nullable: false
    active_pages:
      type: boolean
      label: 'Remember collapsed state on active pages'
      translatable: false
      nullable: false
    slide_type:
      type: integer
      label: 'Default animation type'
      translatable: false
      nullable: false
    slide_speed:
      type: integer
      label: 'Animation speed'
      translatable: false
      nullable: false

# Block instance settings.
block.block.*.third_party.collapsiblock:
  type: mapping
  label: 'Collapsiblock block instance settings'
  mapping:
    collapse_action:
      type: integer
      label: 'Block collapse behavior'
