module:
  acquia_cms_article: 0
  acquia_cms_common: 0
  acquia_cms_document: 0
  acquia_cms_image: 0
  acquia_cms_page: 0
  acquia_cms_person: 0
  acquia_cms_place: 0
  acquia_cms_site_studio: 0
  acquia_cms_toolbar: 0
  acquia_cms_video: 0
  action: 0
  address: 0
  addtoany: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  attachinline: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  bulk_update_fields: 0
  ckeditor: 0
  cohesion: 0
  cohesion_base_styles: 0
  cohesion_breakpoint_indicator: 0
  cohesion_custom_styles: 0
  cohesion_elements: 0
  cohesion_javascript_element: 0
  cohesion_style_guide: 0
  cohesion_style_helpers: 0
  cohesion_sync: 0
  cohesion_templates: 0
  cohesion_tome: 0
  cohesion_website_settings: 0
  collapsiblock: 0
  color: 0
  comment: 0
  config: 0
  config_filter: 0
  config_ignore: 0
  config_rewrite: 0
  config_token: 0
  contact: 0
  content_moderation: 0
  context: 0
  context_ui: 0
  contextual: 0
  crop: 0
  ctools: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  default_content: 0
  dx8_addtoany: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  editor: 0
  editor_advanced_link: 0
  entity_browser: 0
  entity_clone: 0
  entity_reference_revisions: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  focal_point: 0
  geocoder: 0
  geocoder_address: 0
  geocoder_field: 0
  geocoder_geofield: 0
  geofield: 0
  glossify: 0
  glossify_taxonomy: 0
  hal: 0
  help: 0
  history: 0
  image: 0
  imce: 0
  language: 0
  link: 0
  linkit: 0
  media: 0
  media_entity_download: 0
  media_library: 0
  melt_cms_article: 0
  melt_cms_page: 0
  melt_glossify: 0
  melt_logging: 0
  melt_modal: 0
  melt_sticky_drawer: 0
  menu_link_attributes: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  metatag_facebook: 0
  metatag_open_graph: 0
  metatag_segment: 0
  metatag_twitter_cards: 0
  metatag_verification: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  quickedit: 0
  rdf: 0
  rest: 0
  scheduler: 0
  scheduler_content_moderation_integration: 0
  search: 0
  seckit: 0
  serialization: 0
  settings_tray: 0
  shortcut: 0
  simple_sitemap: 0
  sitemap: 0
  sitestudio_page_builder: 0
  smart_trim: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  tome: 0
  tome_base: 0
  tome_static: 0
  tome_static_find_and_replace: 0
  tome_static_include_paths: 0
  tome_sync: 0
  toolbar: 0
  tour: 0
  update: 0
  upgrade_status: 0
  user: 0
  views_ui: 0
  workflows: 0
  yaml_editor: 0
  pathauto: 1
  views: 10
  standard: 1000
  eu_cookie_compliance: 1001
theme:
  bartik: 0
  seven: 0
  stable: 0
  cohesion_theme: 0
  claro: 0
  acquia_claro: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
